# Generated by Django 4.2.7 on 2023-11-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='email',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
