# Generated by Django 4.2.7 on 2023-11-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_profiles_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='is_verified',
            field=models.BooleanField(default=False, max_length=10),
        ),
    ]
